version: 2
updates:
    -   package-ecosystem: maven
        directory: "/"
        schedule:
            interval: daily
            time: "09:00"
            timezone: Etc/GMT+8
        open-pull-requests-limit: 10
        labels:
            - area/dependencies
        allow:
            -   dependency-name: io.netty:netty-bom
            -   dependency-name: org.bouncycastle:bcpkix-jdk15on
            -   dependency-name: org.fusesource.jansi:jansi
            -   dependency-name: ch.qos.logback:logback-classic
            -   dependency-name: org.junit.jupiter:junit-jupiter-engine
            -   dependency-name: org.graalvm.sdk:graal-sdk
            -   dependency-name: org.graalvm.nativeimage:svm
            -   dependency-name: org.graalvm.nativeimage:native-image-maven-plugin
                dependency-type: all
        rebase-strategy: auto
